## Project
name: tasty_bytes
version: "1.0"
config-version: 2
profile: tasty_bytes

## Sources
model-paths: [models]
analysis-paths: [analysis]
test-paths: [tests]
seed-paths: [seeds]
macro-paths: [macros]
snapshot-paths: [snapshots]

## Target
target-path: target
clean-targets: [target, dbt_modules]

vars:
  env_zone_databases:
    dev:
      raw: DEV_RAW
      standard: DEV_STANDARD
      refined: DEV_REFINED
      consumption: DEV_CONSUMPTION
    prod:
      raw: PRD_RAW
      standard: PRD_STANDARD
      refined: PRD_REFINED
      consumption: PRD_CONSUMPTION
  env_zone_schemas:
    raw: TASTYBYTES
    standard: TASTYBYTES
    refined: TASTYBYTES
    consumption: TASTYBYTES
  env_zone_warehouses:
    dev:
      raw: DEV_RAW_WH
      standard: DEV_STANDARD_WH
      refined: DEV_REFINED_WH
      consumption: DEV_CONSUMPTION_WH
    prod:
      raw: PRD_RAW_WH
      standard: PRD_STANDARD_WH
      refined: PRD_REFINED_WH
      consumption: PRD_CONSUMPTION_WH

## Models
models:
  tasty_bytes:
    raw:
      +database: "{{ var('env_zone_databases').get(target.name, {}).get('raw', target.database) }}"
      +schema: "{{ var('env_zone_schemas').get('raw', target.schema) }}"
      +materialized: view
      +snowflake_warehouse: "{{ var('env_zone_warehouses').get(target.name, {}).get('raw', target.warehouse | default('DEV_RAW_WH')) }}"
      +tags: ['zone:raw']
      tastybytes:
        +tags: ['domain:tastybytes']
    standard:
      +database: "{{ var('env_zone_databases').get(target.name, {}).get('standard', target.database) }}"
      +schema: "{{ var('env_zone_schemas').get('standard', target.schema) }}"
      +materialized: table
      +snowflake_warehouse: "{{ var('env_zone_warehouses').get(target.name, {}).get('standard', target.warehouse | default('DEV_STANDARD_WH')) }}"
      +tags: ['zone:standard']
      tastybytes:
        +tags: ['domain:tastybytes']
    refined:
      +database: "{{ var('env_zone_databases').get(target.name, {}).get('refined', target.database) }}"
      +schema: "{{ var('env_zone_schemas').get('refined', target.schema) }}"
      +materialized: table
      +snowflake_warehouse: "{{ var('env_zone_warehouses').get(target.name, {}).get('refined', target.warehouse | default('DEV_REFINED_WH')) }}"
      +tags: ['zone:refined']
      tastybytes:
        +tags: ['domain:tastybytes']
    consumption:
      +database: "{{ var('env_zone_databases').get(target.name, {}).get('consumption', target.database) }}"
      +schema: "{{ var('env_zone_schemas').get('consumption', target.schema) }}"
      +materialized: view
      +snowflake_warehouse: "{{ var('env_zone_warehouses').get(target.name, {}).get('consumption', target.warehouse | default('DEV_CONSUMPTION_WH')) }}"
      +secure: true
      +tags: ['zone:consumption']
      tastybytes:
        +tags: ['domain:tastybytes']
